MvcApplication.Web/Controllers/CategoryController.cs
using System.Web.Mvc;
using MvcApplication.DataContract;
using MvcApplication.Entities;
using MvcApplication.Services;

namespace MvcApplication.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categories;

        public CategoryController(ICategoryService category)
        {
            _categories = category;
        }

        public ActionResult Index()
        {
            return View(_categories.WithProductCount());
        }
       
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Category model, string isDeleted)
        {
            if (isDeleted != null)
            {
                if (_categories.InUsage(model.Id)) return View("CategoryInUsage");
                _categories.Delete(model.Id);
            }
            else
            {
                if (!ModelState.IsValid) return View(model);
                _categories.AddOrUpdate(new CategoryDataContract(model));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var category = (id == null) ? new CategoryDataContract() : _categories.Get(id.Value);
            if (category != null) return View(new Category(category));
            return new HttpNotFoundResult("Нет категории с id = " + id);
        }
    }
}

MvcApplication.Web/Views/Category/CategoryInUsage.cshtml
@{
    ViewBag.Title = "Категория используется";
}

<h2>@ViewBag.Title</h2>
<p>
    Нельзя удалить категорию товаров, если она содержит товары.
</p>

<a href ="/Home/Index">Вернуться назад</a>

MvcApplication.Web/Views/Category/Edit.cshtml
@using System.Linq
@using MvcApplication.Entities

@model Category
@{
    ViewBag.Title = "Описание категории";
}
<h2>@ViewBag.Title</h2>          


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </fieldset>
    <br/>

<div>
    @Html.ActionLink("Назад к списку", "Index", null, new { @class = "btn btn-default" })
    <button class='btn btn-success' @(User.IsInRole("Admin") ? "" : "disabled")>Сохранить изменения</button>
       
    @if (Model.Id != 0)
    {
        <input type="submit" name="isDeleted" class='btn btn-danger' @(User.IsInRole("Admin") ? "" : "disabled") value="Удалить категорию"/>
    }
</div>

}

MvcApplication.Web/Views/Category/Index.cshtml
@using System.Linq
@using System.Collections.Generic
@using MvcApplication.DataContract

@model ICollection<KeyValuePair<CategoryDataContract, int>>

@{
    ViewBag.Title = "Категории товаров";
}

<h2>@ViewBag.Title</h2>

@if (!Model.Any())
{
    <p>Категории товаров не заданы.</p>
}
else
{
    <table class="table">
        <tr>
            <th>Название категории</th>
            <th>
                Количество товаров в данной категории
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Key.Id })">&#9998; @item.Key.Name</a>
                </td>
      
                <td>
                    @if (item.Value > 0)
                    {
                        @item.Value
                    }
                    else
                    {
                        @: -
                    }
                </td>
            </tr>
        }
    </table>
}

@using (Html.BeginForm("Edit", "Category", FormMethod.Get))
{
    <button class='btn btn-success' @(User.IsInRole("Admin") ? "" : "disabled")>
        Новая категория
    </button>
}