MvcApplication.Web/Controllers/DefaultController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MvcApplication.DataContract;
using MvcApplication.Entities;
using MvcApplication.Models;
using MvcApplication.Services;

namespace MvcApplication.Controllers
{
    public class DefaultController : Controller
    {
        private readonly IProductService _products;
        private readonly ICategoryService _categories;
        private readonly ICartService _cart;
        private readonly IFormsAuthenticationService _authentication;

        public DefaultController(IProductService products, ICategoryService categories, ICartService cart, IFormsAuthenticationService authentication)
        {
            _products = products;
            _categories = categories;
            _cart = cart;
            _authentication = authentication;
        }

        public ActionResult Index(ProductsAndCategories model, FilterModel filter, string isCart)
        {
            ICollection<CartItem> cartItems = (model != null) ? model.CartItems : null;
            filter = filter ?? ((model != null) ? model.Filter : null);
            model = AddCategories(_products.Filter(filter), filter);
            var user = User.GetAccount();
            var accountId = (user == null) ? null : user.AccountId;
            if (cartItems != null)
            {
                var oldCart = (accountId.HasValue)
                    ? new HashSet<int>(_cart.Filter(accountId.Value).Select(x => x.ProductId))
                    : new HashSet<int>();
                foreach (var item in cartItems)
                {
                        if (item.Count > 1 && !oldCart.Contains(item.ProductId)) item.IsSelected = "on";
                }
                model.CartItems = cartItems;

                var cart = cartItems.Where(x => x.IsSelected != null).Select(x => new CartItemDataContract(x));
                string newUserName = _cart.AddOrUpdate(accountId, cart.ToList());
                _authentication.SignIn(newUserName, true);
            }
            else if (accountId.HasValue)
            {
                cartItems = _cart.Filter(accountId.Value).Select(x => new CartItem(x) { IsSelected = "on" }).ToList();
                model.CartItems = cartItems;
            }
            if (isCart != null) return RedirectToAction("Cart", model.Filter);
            return View(model);
        }

        [HttpGet]
        public ActionResult Cart(FilterModel filter)
        {
            var user = User.GetAccount();
            if (user == null || !user.AccountId.HasValue) return View(AddCategories(new ProductDataContract[0], filter));
            var model = AddCategories(_cart.GetProducts(user.AccountId.Value), filter);
            model.CartItems = _cart.Filter(user.AccountId.Value).Select(x => new CartItem(x) { IsSelected = "on" }).ToList();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Cart(ProductsAndCategories model, FilterModel filter, string isBuy)
        {
            filter = filter ?? ((model != null) ? model.Filter : null);
            var user = User.GetAccount();
            var cart = (from item in model.CartItems
                        where item.IsSelected != null
                        select new CartItemDataContract(item)
                       ).ToList();
            _cart.AddOrUpdate(user.AccountId.Value, cart);

            if (isBuy != null && cart.Any())
            {
                if (User.IsNotGuest())
                {
                    _cart.FinishBuy(User.GetAccount().AccountId);
                    return RedirectToAction("Buy");
                }
                return RedirectToAction("Register", "Home");
            }
            var newModel = AddCategories(_cart.GetProducts(user.AccountId.Value), filter);
            newModel.CartItems = model.CartItems;
            return View(newModel);
        }

        [Authorize(Roles = "Admin,Seller")]
        [HttpPost]
        public ActionResult Edit(ProductsAndCategories model, string isDeleted)
        {
            if (isDeleted != null)
            {
                _products.Delete(model.Product.Id);
            }
            else
            {
                if (!ModelState.IsValid) return View(AddCategories(model.Products, model.Filter));
                _products.AddOrUpdate(new ProductDataContract(model.Product));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var product = (id == null) ? new ProductDataContract() : _products.Get(id.Value);
            if (product != null) return View(AddCategories(new[] { product}));
            return new HttpNotFoundResult("Нет продукта с id = " + id);
        }

        private ProductsAndCategories AddCategories(IList<ProductDataContract> products, FilterModel filter = null)
        {
            return new ProductsAndCategories(products, _categories.GetAll()) { Filter = filter};
        }

        public ActionResult Buy()
        {
            return View();
        }
    }
}

MvcApplication.Web/Views/Default/Buy.cshtml
@{
    ViewBag.Title = "Спасибо за покупку!";
}

<h2>@ViewBag.Title</h2>
<div>
    <p>Спасибо за покупку! </p> 
    <p>
        Наш менеджер свяжется с Вами по вопросам оплаты и доставки товаров по указанному Вами адресу электронной почты.
        Если адрес электронной почты устарел или Вы хотите его заменить, войдите в
        @Html.ActionLink("Личный кабинет", "Register", "Account", null, new {@class = "btn btn-xs btn-primary"})
    </p>
    <p> Приходите к нам ещё! </p>
</div>

@Html.ActionLink("Вернуться к товарам","Index", "Default", null, new {@class="btn btn-lg btn-default"}) 

MvcApplication.Web/Views/Default/Cart.cshtml
@using System.Linq
@using System.Collections.Generic
@using MvcApplication.Models

@model ProductsAndCategories

@{
    ViewBag.Title = "Корзина";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
  if (!Model.Products.Any())
  {
    <p>Товары отсутствуют.</p>
  }
  else
  {
    <table class="table">
      <tr>
        <th> Выбор </th>
        <th>Наименование </th>
        <th>Цена</th>
        <th>
            Описание товара
        </th>
        <th>Категория товара</th>
      </tr>

    @for (int i = 0; i < Model.Products.Count; i++)
    {
      var product = Model.Products[i];  
      <tr>
        <td>
                @{ var item = Model.GetCartItem(product.Id); }
                <input type="checkbox" name="CartItems[@i].IsSelected" @(item.IsSelected != null ? "checked" : "")/>
                <input type="number" name="CartItems[@i].Count" value="@item.Count" min=1 />
                <input type="hidden" name="CartItems[@i].ProductId" value="@product.Id"/>
            шт.
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id = product.Id })">&#9998; @product.Name</a>
        </td>
      
        <td>
            @product.Price &#8381;
        </td>
        <td>
            @product.Description
        </td>

        <td>
            @if (product.CategoryId != null)
            {
                @Model.GetCategoryName(product.CategoryId)
            }
            else
            {
                <i>без категории</i>
            }
        </td>
      </tr>
    }
    </table>
  }
  
    @Html.ActionLink("Вернуться к товарам", "Index", "Default", Model.Filter, new { @class = "btn btn-default" })

    if (Model.Products.Any())
    {
        <button class='btn btn-primary'>
            Изменить выбор
        </button>
        <button name="isBuy" class='btn btn-success'>
            Оформить покупку
        </button>
    }
  

  
}

MvcApplication.Web/Views/Default/Edit.cshtml
@using System.Linq
@using MvcApplication.Entities
@using MvcApplication.Models

@model ProductsAndCategories
@{
    ViewBag.Title = "Описание товара";
}
<h2>@ViewBag.Title</h2>          


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(model => model.Product.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Product.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Product.Name)
            @Html.ValidationMessageFor(model => model.Product.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Product.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Product.Description)
            @Html.ValidationMessageFor(model => model.Product.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Product.CategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Product.CategoryId, Model.Categories, "-", new { style = "width: 150px;", })
            @Html.ValidationMessageFor(model => model.Product.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Product.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Product.Price)
            @Html.ValidationMessageFor(model => model.Product.Price)
        </div>

    </fieldset>
    <br/>

<div>
    @Html.ActionLink("Назад к списку", "Index", null, new { @class = "btn btn-default" })
    <button class='btn btn-success' @(User.IsInRole("Admin") ? "" : "disabled")>Сохранить изменения</button>
       
    @if (Model.Product.Id != 0)
    {
        <input type="submit" name="isDeleted" class='btn btn-danger' @(User.IsInRole("Admin") ? "" : "disabled") value="Удалить товар"/>
    }
</div>

}

MvcApplication.Web/Views/Default/Index.cshtml
@using System.Linq
@using System.Collections.Generic
@using MvcApplication.Models

@model ProductsAndCategories

@{
    ViewBag.Title = "Список товаров";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div class="bg-info" style="padding: 10px; text-align: right;">
        Интересующая Вас категория товара:
        @Html.DropDownListFor(x => x.Filter.CategoryId, Model.Categories, "-", new { style = "width: 230px;", })
        с ценой от
        @Html.EditorFor(x => x.Filter.MinPrice)
        до
        @Html.EditorFor(x => x.Filter.MaxPrice)        
        &#8381;
        <br/>
        и содержит слова: 
        @Html.EditorFor(x => x.Filter.Text) 
        @Html.RadioButtonFor(x => x.Filter.OnlyName, "true", true)
        в наименовании товара
        @Html.RadioButtonFor(x => x.Filter.OnlyName, "false")
        и в описании.

        <button class='btn btn-default'>Выбрать</button>
        @Html.ActionLink("Очистить", "Index", null, new { @class = "btn btn-default" })

    </div>
  <br/>

  if (!Model.Products.Any())
  {
    <p>Товары отсутствуют.</p>
  }
  else
  {
    <table class="table">
      <tr>
        <th> Выбор </th>
        <th>Наименование </th>
        <th>Цена</th>
        <th>
            Описание товара
        </th>
        <th>Категория товара</th>
      </tr>

    @for (int i = 0; i < Model.Products.Count; i++)
    {
      var product = Model.Products[i];  
      <tr>
        <td>
                @{ var item = Model.GetCartItem(product.Id); }
                <input type="checkbox" name="CartItems[@i].IsSelected" @(item.IsSelected != null ? "checked" : "")/>
                <input type="number" name="CartItems[@i].Count" value="@item.Count" min=1 />
                <input type="hidden" name="CartItems[@i].ProductId" value="@product.Id"/>
            шт.
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id = product.Id })">&#9998; @product.Name</a>
        </td>
      
        <td>
            @product.Price &#8381;
        </td>
        <td>
            @product.Description
        </td>

        <td>
            @if (product.CategoryId != null)
            {
                @Model.GetCategoryName(product.CategoryId)
            }
            else
            {
                <i>без категории</i>
            }
        </td>
      </tr>
    }
    </table>
  }
  
    <button class='btn btn-primary'>
        Подтвердить выбор
    </button>
    
    <button class='btn btn-success' name="isCart">
        Перейти в корзину
    </button>
   
    if (User.IsInRole("Seller") || User.IsInRole("Admin"))
    {
        @Html.ActionLink("Добавить товар", "Edit", "Default", null, new { @class = "btn btn-info" })
    }
}