MvcApplication.Web/Controllers/GroupController.cs
using System.Linq;
using System.Web.Mvc;
using MvcApplication.DataContract;
using MvcApplication.Entities;
using MvcApplication.Models;
using MvcApplication.Services;

namespace MvcApplication.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groups;
        private readonly IAccountService _accounts;

        public GroupController(IGroupService group, IAccountService accounts)
        {
            _groups = group;
            _accounts = accounts;
        }

        public ActionResult Index()
        {
            return View(_groups.WithAccountCount());
        }
       
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(EditGroupModel model, string isDeleted)
        {
            if (isDeleted != null)
            {
                if (_groups.InUsage(model.Group.Id)) return View("GroupInUsage");
                _groups.Delete(model.Group.Id);
            }
            else
            {
                /*
                if (!ModelState.IsValid)
                {
                    model.Group.Accounts = _groups.GetAccounts(model.Group.Id).ConvertAll(x => new Account(x));
                    model.AllAccounts = _accounts.GetAll();
                    return View(model);
                }
                 */
                var selected = model.Group.Accounts.Where(x => x.IsSelected != null).Select(x => x.Id);
                _groups.AddOrUpdate(new GroupDataContract(model.Group), selected.ToList());
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var group = (id == null) ? new GroupDataContract() : _groups.Get(id.Value);
            var model = new Group(group) {Accounts = _groups.GetAccounts(id).ConvertAll(x => new Account(x))};
            if (group != null) return View(new EditGroupModel { Group = model, AllAccounts = _accounts.GetAll() });
            return new HttpNotFoundResult("Нет категории с id = " + id);
        }
    }
}

MvcApplication.Web/Views/Group/Edit.cshtml
@using System.Linq
@using MvcApplication.Models

@model EditGroupModel
@{
    ViewBag.Title = "Управление группой";
}
<h2>@ViewBag.Title</h2>          


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        @Html.HiddenFor(model => model.Group.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Group.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Group.Name)
            @Html.ValidationMessageFor(model => model.Group.Name)
        </div>
    </div>
    <br/>

    <div>
        @Html.LabelFor(model => model.Group.Accounts)
        <ol>
            @for (int i = 0; i < Model.AllAccounts.Count; i++)
            {
                var account = Model.AllAccounts[i];  
                <li>
                    <input type="checkbox" name="Group.Accounts[@i].IsSelected" @(Model.InGroup(account.Id) ? "checked" : "") />
                    <input type="hidden" name="Group.Accounts[@i].Id" value="@account.Id"/>
                    @account.Login
                </li>
            }
        </ol>
        @Html.ValidationMessageFor(model => model.Group.Accounts)
    </div>
    <br/>

<div>
    @Html.ActionLink("Назад к списку", "Index", null, new { @class = "btn btn-default" })
    <button class='btn btn-success' @(User.IsInRole("Admin") ? "" : "disabled")>Сохранить изменения</button>
       
    @if (Model.Group.Id != 0)
    {
        <input type="submit" name="isDeleted" class='btn btn-danger' @(User.IsInRole("Admin") ? "" : "disabled") value="Удалить категорию"/>
    }
</div>

}

MvcApplication.Web/Views/Group/GroupInUsage.cshtml
@{
    ViewBag.Title = "Группа используется";
}

<h2>@ViewBag.Title</h2>
<p>
    Удаление группы пользователей при наличии в ней пользователей запрещено в связи с частыми ошибками.
</p>

<a href ="@Url.Action("Index")">Вернуться назад</a>

MvcApplication.Web/Views/Group/Index.cshtml
@using System.Linq
@using System.Collections.Generic
@using MvcApplication.DataContract

@model ICollection<KeyValuePair<GroupDataContract, int>>

@{
    ViewBag.Title = "Список групп";
}

<h2>@ViewBag.Title</h2>

@if (!Model.Any())
{
    <p>Группы пользователей отсутствуют.</p>
}
else
{
    <table class="table">
        <tr>
            <th>Название группы</th>
            <th>
                Количество пользователей в группе
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Key.Id })">&#9998; @item.Key.Name</a>
                </td>
      
                <td>
                    @if (item.Value > 0)
                    {
                        @item.Value
                    }
                    else
                    {
                        @: -
                    }
                </td>
            </tr>
        }
    </table>
}

@using (Html.BeginForm("Edit", "Group", FormMethod.Get))
{
    <button class='btn btn-success' @(User.IsInRole("Admin") ? "" : "disabled")>
        Новая группа
    </button>
}